# Generated by Django 5.1.1 on 2024-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='earningReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('ageMin', models.IntegerField(default=18)),
                ('ageMax', models.IntegerField(default=100)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
