# Generated by Django 5.1.1 on 2024-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_postal_code',
            field=models.CharField(max_length=100),
        ),
    ]
