# Generated by Django 5.1.1 on 2024-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='had_BD_gift',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_BD_gift',
            field=models.DateField(default=None, null=True),
        ),
    ]
