# Generated by Django 5.1.1 on 2024-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='count_pizza',
            field=models.IntegerField(default=0),
        ),
    ]
