# Generated by Django 5.1.1 on 2024-10-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_count_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='had_BD_gift',
            field=models.BooleanField(default=False),
        ),
    ]
