# Generated by Django 5.1.1 on 2024-10-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_had_bd_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='address_number_street',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
