# Generated by Django 5.1.1 on 2024-10-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_address_customer_address_number_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_city',
            field=models.CharField(max_length=100),
        ),
    ]
