# Generated by Django 5.1.1 on 2024-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=15, unique=True)),
                ('percentage', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
