# Generated by Django 5.1.1 on 2024-10-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount',
            new_name='percentage',
        ),
    ]
