# Generated by Django 5.1.1 on 2024-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='postal_code_area',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
