# Generated by Django 5.1.1 on 2024-10-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_deliveryperson_postal_code_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_person',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
