# Generated by Django 5.1.1 on 2024-10-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
        ('orders', '0003_remove_delivery_delivery_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Ingredients',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.dessert'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.drink'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.pizza'),
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
