# Generated by Django 5.1.1 on 2024-10-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_all_ingredients_pizza_ingredients_alter_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='desserts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.dessert'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.drink'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'),
        ),
    ]
