# Generated by Django 5.1.1 on 2024-10-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_desserts_remove_order_drinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
    ]
