# Generated by Django 5.1.1 on 2024-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_discount_code',
            field=models.BooleanField(default=False),
        ),
    ]
