# Generated by Django 5.1.1 on 2024-10-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_has_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
