# Generated by Django 5.1.1 on 2024-10-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_deliveryperson_order_estimated_delivery_time'),
        ('orders', '0007_pizza_is_vegan_pizza_is_vegetarian'),
    ]

    operations = [
    ]
