# Generated by Django 5.1.1 on 2024-10-05 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_assigned_delivery_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_delivery_person',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliveryperson'),
        ),
    ]
