# Generated by Django 5.1.1 on 2024-10-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_assigned_delivery_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ingredients',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Your order is being prepared', 'Your order is being prepared'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=100),
        ),
    ]
