# Generated by Django 5.1.1 on 2024-10-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_all_ingredients_vegetarian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='address_city',
            field=models.CharField(default='Lyon', max_length=100),
        ),
    ]
